# Generated by Django 3.2.12 on 2022-03-29 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='logo',
            new_name='file',
        ),
        migrations.AddField(
            model_name='news',
            name='is_video',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='published_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
